version: "3.8"
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "chitchat"
    volumes:
      # - ./init:/docker-entrypoint-initdb.d/
      - ./pgdata:/var/lib/postgresql/data
  backend:
    image: bmcglauser/chit-chat-server
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_DATABASE: chitchat
      JWT_SECRET: a
    volumes:
      - ./server:/app
      - /app/node_modules
    links:
      - db
  frontend:
    image: bmcglauser/chit-chat-client
    depends_on:
      - backend
    ports:
      - "3000:80"
    environment:
      REACT_APP_SERVER_URI: "http://localhost:5000"
