const languageMap = {
  ES: {
    "Recent Activity": "Última actividad",
    "Chat Rooms": "Salas de chat",
    "My Assignments": "Mis tareas",
    Assignments: "Tareas",
    "Team Chat": "Chat de equipo",
    Download: "Descargar",
    "Download All": "Descargar todo",
    download: "descargar",
    Upload: "Subir",
    upload: "subir",
    "Nothing uploaded": "Nada subido",
    "No comments": "Ningún commentario",
    "Nothing to show": "Nada a mostrar",
    Team: "Equipo",
    Teammates: "Compañeros de equipo",
    Teachers: "Profesores",
    Students: "Estudiantes",
    Tasks: "Tareas",
    Resources: "Recursos",
  },
  FR: {
    "Recent Activity": "Nouveautés",
    "Chat Rooms": "Salles de discussion",
    "My Assignments": "Mes devoirs",
    Assignments: "Devoirs",
    "Team Chat": "Discussion d'équipe",
    Download: "Télécharger",
    "Download All": "Tout télécharger",
    download: "télécharger",
    Upload: "Télécharger",
    upload: "télécharger",
    "Nothing uploaded": "Rien téléchargé",
    "No comments": "Aucun commentaire",
    "Nothing to show": "Rien à voir",
    Team: "Équipe",
    Teammates: "Co-équipiers",
    Teachers: "Professeurs",
    Students: "Étudiants",
    Tasks: "Tâches",
    Resources: "Ressources",
  },
  EN: {
    "Recent Activity": "Recent Activity",
    "Chat Rooms": "Chat Rooms",
    "My Assignments": "My Assignments",
    Assignments: "Assignments",
    "Team Chat": "Team Chat",
    Download: "Download",
    "Download All": "Download All",
    download: "download",
    Upload: "Upload",
    upload: "upload",
    "Nothing uploaded": "Nothing uploaded",
    "No comments": "No comments",
    "Nothing to show": "Nothing to show",
    Team: "Team",
    Teammates: "Teammates",
    Teachers: "Teachers",
    Students: "Students",
    Tasks: "Tasks",
    Resources: "Resources",
  },
};

export default function translate(str, lang) {
  return languageMap[lang][str];
}
