const languageMap = {
  ES: {
    "Recent Activity": "Última Actividad",
    "Chat Rooms": "Salas de Chat",
    "My Assignments": "Mis Tareas",
    Assignments: "Tareas",
    "Team Chat": "Chat de Equipo",
    Download: "Descargar",
    "Download All": "Descargar Todo",
    download: "descargar",
    Upload: "Subir",
    upload: "subir",
    "Nothing uploaded": "Nada subido",
    "No comments": "Ningún commentario",
    Team: "Equipo",
    Teammates: "Compañeros de Equipo",
    Teachers: "Profesores",
    Students: "Estudiantes",
    Tasks: "Tareas",
    Resources: "Recursos",
  },
  EN: {
    "Recent Activity": "Recent Activity",
    "Chat Rooms": "Chat Rooms",
    "My Assignments": "My Assignments",
    Assignments: "Assignments",
    "Team Chat": "Team Chat",
    Download: "Download",
    "Download All": "Download All",
    download: "download",
    Upload: "Upload",
    upload: "upload",
    "Nothing uploaded": "Nothing uploaded",
    "No comments": "No comments",
    Team: "Team",
    Teammates: "Teammates",
    Teachers: "Teachers",
    Students: "Students",
    Tasks: "Tasks",
    Resources: "Resources",
  },
};

export default function translate(str, lang) {
  return languageMap[lang][str];
}
