export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const GET_ASSIGNMENT_PREVIEWS_BY_COURSE =
  "GET_ASSIGNMENT_PREVIEWS_BY_COURSE";

export const GET_ALL_MESSAGES = "GET_ALL_MESSAGES";
export const GET_ROOM_USERS = "GET_ROOM_USERS";

export const GET_STUDENTS_BY_COURSE = "GET_STUDENTS_BY_COURSE";
export const GET_STUDENT_BY_ROOM = "GET_STUDENT_BY_ROOM";
export const GET_STUDENTS_WITH_SISTER_COURSE =
  "GET_STUDENTS_WITH_SISTER_COURSE";

export const GET_ASSIGNMENT = "GET_ASSIGNMENT";
