export const GET_CURRENT_USER = "GET_CURRENT_USER";

export const GET_ALL_MESSAGES = "GET_ALL_MESSAGES";
export const GET_ROOM_USERS = "GET_ROOM_USERS";

export const GET_STUDENTS_BY_COURSE = "GET_STUDENTS_BY_COURSE";
export const GET_STUDENT_BY_ROOM = "GET_STUDENT_BY_ROOM";
export const GET_STUDENTS_WITH_SISTER_COURSE =
  "GET_STUDENTS_WITH_SISTER_COURSE";
export const REGISTER_STUDENT = "REGISTER_STUDENT";

export const GET_ASSIGNMENT = "GET_ASSIGNMENT";
export const GET_ASSIGNMENT_PREVIEWS_BY_COURSE =
  "GET_ASSIGNMENT_PREVIEWS_BY_COURSE";
export const GET_ASSIGNMENT_PREVIEWS_BY_ROOM =
  "GET_ASSIGNMENT_PREVIEWS_BY_ROOM";
export const LIKE_ASSIGNMENT = "LIKE_ASSIGNMENT";
export const COMMENT_ASSIGNMENT = "COMMENT_ASSIGNMENT";
export const CLEAR_ASSIGNMENT_UPLOAD = "CLEAR_ASSIGNMENT_UPLOAD";
export const DISMISS_ASSIGNMENT = "DISMISS_ASSIGNMENT";

export const DELETE_COMMENT = "DELETE_COMMENT";

export const SET_ERROR = "SET_ERROR";

export const EDIT_STUDENT_NAME = "EDIT_STUDENT_NAME";

export const GET_ALL_RESOURCES = "GET_ALL_RESOURCES";
